In [1]:
import pandas as pd
import numpy as np
import json 
from sklearn.preprocessing import MinMaxScaler

## Read In Main CSV from Kaggle

In [2]:
file = "winemag-data_first150k.csv"

In [3]:
wine_df = pd.read_csv(file)

In [4]:
wine_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [5]:
wine_df.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'variety', 'winery'],
      dtype='object')

## Clean Main CSV Data

In [6]:
reduced_wine_df = wine_df.loc[:, ["country", "points", "price", "province", "region_1", "variety", "winery"]]
reduced_wine_df

,country,points,price,province,region_1,variety,winery
0,US,96,235.0,California,Napa Valley,Cabernet Sauvignon,Heitz
1,Spain,96,110.0,Northern Spain,Toro,Tinta de Toro,Bodega Carmen Rodríguez
2,US,96,90.0,California,Knights Valley,Sauvignon Blanc,Macauley
3,US,96,65.0,Oregon,Willamette Valley,Pinot Noir,Ponzi
4,France,95,66.0,Provence,Bandol,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...
150925,Italy,91,20.0,Southern Italy,Fiano di Avellino,White Blend,Feudi di San Gregorio
150926,France,91,27.0,Champagne,Champagne,Champagne Blend,H.Germain
150927,Italy,91,20.0,Southern Italy,Fiano di Avellino,White Blend,Terredora
150928,France,90,52.0,Champagne,Champagne,Champagne Blend,Gosset
150929,Italy,90,15.0,Northeastern Italy,Alto Adige,Pinot Grigio,Alois Lageder

In [7]:
reduced_wine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150930 entries, 0 to 150929
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   country   150925 non-null  object
 1   points    150930 non-null  int64
 2   price     137235 non-null  float64
 3   province  150925 non-null  object
 4   region_1  125870 non-null  object
 5   variety   150930 non-null  object
 6   winery    150930 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 8.1+ MB

In [8]:
reduced_wine_df.count()

country     150925
points      150930
price       137235
province    150925
region_1    125870
variety     150930
winery      150930
dtype: int64

In [9]:
reduced_wine_df2 = reduced_wine_df.dropna(how="any")
reduced_wine_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 114393 entries, 0 to 150929
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   country   114393 non-null  object
 1   points    114393 non-null  int64
 2   price     114393 non-null  float64
 3   province  114393 non-null  object
 4   region_1  114393 non-null  object
 5   variety   114393 non-null  object
 6   winery    114393 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 7.0+ MB

In [10]:
reduced_wine_df2.count()

country     114393
points      114393
price       114393
province    114393
region_1    114393
variety     114393
winery      114393
dtype: int64

In [11]:
reduced_wine_df2

,country,points,price,province,region_1,variety,winery
0,US,96,235.0,California,Napa Valley,Cabernet Sauvignon,Heitz
1,Spain,96,110.0,Northern Spain,Toro,Tinta de Toro,Bodega Carmen Rodríguez
2,US,96,90.0,California,Knights Valley,Sauvignon Blanc,Macauley
3,US,96,65.0,Oregon,Willamette Valley,Pinot Noir,Ponzi
4,France,95,66.0,Provence,Bandol,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...
150925,Italy,91,20.0,Southern Italy,Fiano di Avellino,White Blend,Feudi di San Gregorio
150926,France,91,27.0,Champagne,Champagne,Champagne Blend,H.Germain
150927,Italy,91,20.0,Southern Italy,Fiano di Avellino,White Blend,Terredora
150928,France,90,52.0,Champagne,Champagne,Champagne Blend,Gosset
150929,Italy,90,15.0,Northeastern Italy,Alto Adige,Pinot Grigio,Alois Lageder

## Read in CSV Red Wine CSV (From Previous Group's Project)

In [12]:
file2 = "Wine_Reds.csv"

In [13]:
red_wine_df = pd.read_csv(file2)
red_wine_df

                  Variety  Counts   Red?
0              Chardonnay   13775  False
1              Pinot Noir   13625   True
2      Cabernet Sauvignon   12671   True
3               Red Blend    9377   True
4         Sauvignon Blanc    6054  False
..                    ...     ...    ...
614        Bombino Bianco       1    NaN
615             Magliocco       1    NaN
616  Merlot-Petite Verdot       1    NaN
617           Moscofilero       1    NaN
618                Kuntra       1    NaN

[619 rows x 3 columns]

## Clean Red Wine CSV Data

In [14]:
renamed_red_wine = red_wine_df.rename(columns = {'Variety': 'variety', 'Red?': 'red' })
renamed_red_wine

                  variety  Counts    red
0              Chardonnay   13775  False
1              Pinot Noir   13625   True
2      Cabernet Sauvignon   12671   True
3               Red Blend    9377   True
4         Sauvignon Blanc    6054  False
..                    ...     ...    ...
614        Bombino Bianco       1    NaN
615             Magliocco       1    NaN
616  Merlot-Petite Verdot       1    NaN
617           Moscofilero       1    NaN
618                Kuntra       1    NaN

[619 rows x 3 columns]

## Merge Main DataSet w/Red Wine Dataset for types of wine

In [15]:
merge_df = pd.merge(reduced_wine_df2, renamed_red_wine, on="variety")
merge_df

,country,points,price,province,region_1,variety,winery,Counts,red
0,US,96,235.0,California,Napa Valley,Cabernet Sauvignon,Heitz,12671,True
1,US,95,325.0,California,Diamond Mountain District,Cabernet Sauvignon,Hall,12671,True
2,US,90,60.0,California,Mount Veeder,Cabernet Sauvignon,Brandlin,12671,True
3,US,90,40.0,Washington,Red Mountain,Cabernet Sauvignon,Canvasback,12671,True
4,US,90,69.0,Washington,Red Mountain,Cabernet Sauvignon,DeLille,12671,True
...,...,...,...,...,...,...,...,...,...
114388,France,88,19.0,Alsace,Alsace,Tokay Pinot Gris,Rieflé,4,NaN
114389,France,87,41.0,Alsace,Alsace,Tokay Pinot Gris,Rieflé,4,NaN
114390,Italy,84,9.0,Tuscany,Toscana,Chardonnay-Pinot Grigio,Banfi,1,NaN
114391,Spain,84,12.0,Northern Spain,Somontano,Moristel,Alquézar,1,NaN
114392,Australia,87,14.0,Western Australia,Western Australia,Carnelian,Windshaker Ridge,1,NaN

## Clean Merged Data

In [16]:
merge_df2 = merge_df.loc[:, ["country", "points", "price", "province", "region_1", "variety", "winery", "red"]]
merge_df2

,country,points,price,province,region_1,variety,winery,red
0,US,96,235.0,California,Napa Valley,Cabernet Sauvignon,Heitz,True
1,US,95,325.0,California,Diamond Mountain District,Cabernet Sauvignon,Hall,True
2,US,90,60.0,California,Mount Veeder,Cabernet Sauvignon,Brandlin,True
3,US,90,40.0,Washington,Red Mountain,Cabernet Sauvignon,Canvasback,True
4,US,90,69.0,Washington,Red Mountain,Cabernet Sauvignon,DeLille,True
...,...,...,...,...,...,...,...,...
114388,France,88,19.0,Alsace,Alsace,Tokay Pinot Gris,Rieflé,NaN
114389,France,87,41.0,Alsace,Alsace,Tokay Pinot Gris,Rieflé,NaN
114390,Italy,84,9.0,Tuscany,Toscana,Chardonnay-Pinot Grigio,Banfi,NaN
114391,Spain,84,12.0,Northern Spain,Somontano,Moristel,Alquézar,NaN
114392,Australia,87,14.0,Western Australia,Western Australia,Carnelian,Windshaker Ridge,NaN

In [17]:
reduced_wine_df3 = merge_df2.dropna(how="any")
reduced_wine_df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113882 entries, 0 to 114339
Data columns (total 8 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   country   113882 non-null  object
 1   points    113882 non-null  int64
 2   price     113882 non-null  float64
 3   province  113882 non-null  object
 4   region_1  113882 non-null  object
 5   variety   113882 non-null  object
 6   winery    113882 non-null  object
 7   red       113882 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 7.8+ MB

In [18]:
reduced_wine_df3

,country,points,price,province,region_1,variety,winery,red
0,US,96,235.0,California,Napa Valley,Cabernet Sauvignon,Heitz,True
1,US,95,325.0,California,Diamond Mountain District,Cabernet Sauvignon,Hall,True
2,US,90,60.0,California,Mount Veeder,Cabernet Sauvignon,Brandlin,True
3,US,90,40.0,Washington,Red Mountain,Cabernet Sauvignon,Canvasback,True
4,US,90,69.0,Washington,Red Mountain,Cabernet Sauvignon,DeLille,True
...,...,...,...,...,...,...,...,...
114310,Italy,87,24.0,Northeastern Italy,Alto Adige,Silvaner,Abbazia di Novacella,False
114311,Italy,87,24.0,Northeastern Italy,Alto Adige,Silvaner,Abbazia di Novacella,False
114312,Italy,87,24.0,Northeastern Italy,Alto Adige,Silvaner,Abbazia di Novacella,False
114313,France,88,14.0,Alsace,Alsace,Silvaner,Domaines Schlumberger,False
114339,US,88,42.0,California,California,Madeira Blend,V. Sattui,True

In [19]:
reduced_wine_df3 = reduced_wine_df3.replace(
    {1:"red wine", 0:"white wine"})
reduced_wine_df3

,country,points,price,province,region_1,variety,winery,red
0,US,96,235.0,California,Napa Valley,Cabernet Sauvignon,Heitz,red wine
1,US,95,325.0,California,Diamond Mountain District,Cabernet Sauvignon,Hall,red wine
2,US,90,60.0,California,Mount Veeder,Cabernet Sauvignon,Brandlin,red wine
3,US,90,40.0,Washington,Red Mountain,Cabernet Sauvignon,Canvasback,red wine
4,US,90,69.0,Washington,Red Mountain,Cabernet Sauvignon,DeLille,red wine
...,...,...,...,...,...,...,...,...
114310,Italy,87,24.0,Northeastern Italy,Alto Adige,Silvaner,Abbazia di Novacella,white wine
114311,Italy,87,24.0,Northeastern Italy,Alto Adige,Silvaner,Abbazia di Novacella,white wine
114312,Italy,87,24.0,Northeastern Italy,Alto Adige,Silvaner,Abbazia di Novacella,white wine
114313,France,88,14.0,Alsace,Alsace,Silvaner,Domaines Schlumberger,white wine
114339,US,88,42.0,California,California,Madeira Blend,V. Sattui,red wine

In [20]:
renamed_merge_df1 = reduced_wine_df3.rename(columns = {'red': 'type'})
renamed_merge_df1

,country,points,price,province,region_1,variety,winery,type
0,US,96,235.0,California,Napa Valley,Cabernet Sauvignon,Heitz,red wine
1,US,95,325.0,California,Diamond Mountain District,Cabernet Sauvignon,Hall,red wine
2,US,90,60.0,California,Mount Veeder,Cabernet Sauvignon,Brandlin,red wine
3,US,90,40.0,Washington,Red Mountain,Cabernet Sauvignon,Canvasback,red wine
4,US,90,69.0,Washington,Red Mountain,Cabernet Sauvignon,DeLille,red wine
...,...,...,...,...,...,...,...,...
114310,Italy,87,24.0,Northeastern Italy,Alto Adige,Silvaner,Abbazia di Novacella,white wine
114311,Italy,87,24.0,Northeastern Italy,Alto Adige,Silvaner,Abbazia di Novacella,white wine
114312,Italy,87,24.0,Northeastern Italy,Alto Adige,Silvaner,Abbazia di Novacella,white wine
114313,France,88,14.0,Alsace,Alsace,Silvaner,Domaines Schlumberger,white wine
114339,US,88,42.0,California,California,Madeira Blend,V. Sattui,red wine

In [21]:
renamed_merge_df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113882 entries, 0 to 114339
Data columns (total 8 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   country   113882 non-null  object
 1   points    113882 non-null  int64
 2   price     113882 non-null  float64
 3   province  113882 non-null  object
 4   region_1  113882 non-null  object
 5   variety   113882 non-null  object
 6   winery    113882 non-null  object
 7   type      113882 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 7.8+ MB

## Read in Province CSV for Red Wine (From Previous Group's Project) to get Lat/Longs for Province

In [22]:
file3 = "Red_Wine_Provinces.csv"

In [23]:
province_redwine = pd.read_csv(file3)
province_redwine

,Unnamed: 0,province,red_wine_counts,latitude,longtitude
0,0,California,32247,36.778261,-119.417932
1,1,Washington,7303,47.751074,-120.740139
2,2,Tuscany,5542,43.771051,11.248621
3,3,Mendoza Province,3982,-32.889625,-68.852687
4,4,Northern Spain,3877,42.816977,-1.641765
...,...,...,...,...,...
338,338,Central Otago-Marlborough,1,-44.956632,169.398845
339,339,Arcadia,1,34.139729,-118.035345
340,340,Cyprus,1,35.126413,33.429859
341,341,Dolenjska,1,45.755858,15.059233
342,342,Istria,1,45.274502,13.890186

## Merge with Main Data Set with Red Province

In [24]:
merge_df3 = pd.merge(renamed_merge_df1, province_redwine, on="province")
merge_df3

,country,points,price,province,region_1,variety,winery,type,Unnamed: 0,red_wine_counts,latitude,longtitude
0,US,96,235.0,California,Napa Valley,Cabernet Sauvignon,Heitz,red wine,0,32247,36.778261,-119.417932
1,US,95,325.0,California,Diamond Mountain District,Cabernet Sauvignon,Hall,red wine,0,32247,36.778261,-119.417932
2,US,90,60.0,California,Mount Veeder,Cabernet Sauvignon,Brandlin,red wine,0,32247,36.778261,-119.417932
3,US,91,85.0,California,Napa Valley,Cabernet Sauvignon,Michael Mondavi Family Estate,red wine,0,32247,36.778261,-119.417932
4,US,91,60.0,California,Rutherford,Cabernet Sauvignon,Provenance Vineyards,red wine,0,32247,36.778261,-119.417932
...,...,...,...,...,...,...,...,...,...,...,...,...
113866,Spain,85,15.0,Spanish Islands,Vi de la Terra Illes Balears,White Blend,Ànima Negra,white wine,112,24,39.358776,2.735633
113867,Spain,85,15.0,Spanish Islands,Vi de la Terra Illes Balears,White Blend,Ànima Negra,white wine,112,24,39.358776,2.735633
113868,Spain,82,20.0,Spanish Islands,Lanzarote,Rosado,El Grifo,red wine,112,24,39.358776,2.735633
113869,Spain,85,20.0,Spanish Islands,Lanzarote,Malvasia,El Grifo,white wine,112,24,39.358776,2.735633
113870,US,84,75.0,Nevada,Nevada,Zinfandel,Pahrump Valley Winery,red wine,335,1,38.802610,-116.419389

## Clean Main Dataframe

In [25]:
Final_Wine_Data = merge_df3.loc[:, ["country", "points", "price", "province", "region_1", "variety", "winery", "type", "latitude", "longtitude"]]
Final_Wine_Data

,country,points,price,province,region_1,variety,winery,type,latitude,longtitude
0,US,96,235.0,California,Napa Valley,Cabernet Sauvignon,Heitz,red wine,36.778261,-119.417932
1,US,95,325.0,California,Diamond Mountain District,Cabernet Sauvignon,Hall,red wine,36.778261,-119.417932
2,US,90,60.0,California,Mount Veeder,Cabernet Sauvignon,Brandlin,red wine,36.778261,-119.417932
3,US,91,85.0,California,Napa Valley,Cabernet Sauvignon,Michael Mondavi Family Estate,red wine,36.778261,-119.417932
4,US,91,60.0,California,Rutherford,Cabernet Sauvignon,Provenance Vineyards,red wine,36.778261,-119.417932
...,...,...,...,...,...,...,...,...,...,...
113866,Spain,85,15.0,Spanish Islands,Vi de la Terra Illes Balears,White Blend,Ànima Negra,white wine,39.358776,2.735633
113867,Spain,85,15.0,Spanish Islands,Vi de la Terra Illes Balears,White Blend,Ànima Negra,white wine,39.358776,2.735633
113868,Spain,82,20.0,Spanish Islands,Lanzarote,Rosado,El Grifo,red wine,39.358776,2.735633
113869,Spain,85,20.0,Spanish Islands,Lanzarote,Malvasia,El Grifo,white wine,39.358776,2.735633
113870,US,84,75.0,Nevada,Nevada,Zinfandel,Pahrump Valley Winery,red wine,38.802610,-116.419389

In [26]:
Final_Wine_Data.value_counts('type')

type
red wine      81292
white wine    32579
dtype: int64

In [27]:
Final_Wine_Data.value_counts('variety')

variety
Pinot Noir             12193
Chardonnay             12103
Cabernet Sauvignon     10955
Red Blend               8181
Syrah                   5075
                       ...
Zweigelt                   3
Touriga Franca             2
Viognier-Chardonnay        1
Madeira Blend              1
Muskat Ottonel             1
Length: 266, dtype: int64

In [28]:
Final_Wine_Data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 113871 entries, 0 to 113870
Data columns (total 10 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   country     113871 non-null  object
 1   points      113871 non-null  int64
 2   price       113871 non-null  float64
 3   province    113871 non-null  object
 4   region_1    113871 non-null  object
 5   variety     113871 non-null  object
 6   winery      113871 non-null  object
 7   type        113871 non-null  object
 8   latitude    113871 non-null  float64
 9   longtitude  113871 non-null  float64
dtypes: float64(3), int64(1), object(6)
memory usage: 9.6+ MB

In [29]:
Final_Top = Final_Wine_Data.sort_values(by=['points'], ascending=False).head(100)
Final_Top

,country,points,price,province,region_1,variety,winery,type,latitude,longtitude
61541,Italy,100,195.0,Tuscany,Bolgheri Superiore,Red Blend,Giovanni Chiappini,red wine,43.771051,11.248621
63191,Italy,100,460.0,Tuscany,Toscana,Merlot,Tenuta dell'Ornellaia,red wine,43.771051,11.248621
14740,US,100,100.0,California,Russian River Valley,Pinot Noir,Williams Selyem,red wine,36.778261,-119.417932
73169,US,100,65.0,Oregon,Walla Walla Valley (OR),Syrah,Cayuse,red wine,43.804133,-120.554201
16010,US,100,100.0,California,Russian River Valley,Pinot Noir,Williams Selyem,red wine,36.778261,-119.417932
...,...,...,...,...,...,...,...,...,...,...
62998,Italy,98,125.0,Tuscany,Toscana,Cabernet Franc,Le Macchiole,red wine,43.771051,11.248621
62985,Italy,98,130.0,Tuscany,Toscana,Cabernet Franc,Le Macchiole,red wine,43.771051,11.248621
62980,Italy,98,125.0,Tuscany,Toscana,Cabernet Franc,Le Macchiole,red wine,43.771051,11.248621
15786,US,98,150.0,California,Sonoma Coast,Pinot Noir,Evening Land,red wine,36.778261,-119.417932
62696,Italy,98,175.0,Tuscany,Bolgheri Superiore,Red Blend,Tenuta dell'Ornellaia,red wine,43.771051,11.248621

In [30]:
Final_Top.value_counts('type')

type
red wine      88
white wine    12
dtype: int64

## Export Final Wine Data to CSV/Json

In [31]:
Final_Wine_Data.to_csv('Final_Wine_Data.csv', index=True)
Final_Wine_Data.to_json('Final_Wine_Data.csv', index=True)

## Subset Data for All 3 Plotty Charts & Maps

In [32]:
Top_100_Red = Final_Wine_Data.loc[Final_Wine_Data.type == 'red wine'].sort_values(by=['points'], ascending=False).head(100)
Top_100_White = Final_Wine_Data.loc[Final_Wine_Data.type == 'white wine'].sort_values(by=['points'], ascending=False).head(100)

In [33]:
Top_100_Red

,country,points,price,province,region_1,variety,winery,type,latitude,longtitude
73169,US,100,65.0,Oregon,Walla Walla Valley (OR),Syrah,Cayuse,red wine,43.804133,-120.554201
63293,Italy,100,460.0,Tuscany,Toscana,Merlot,Tenuta dell'Ornellaia,red wine,43.771051,11.248621
4206,US,100,215.0,California,Stags Leap District,Cabernet Sauvignon,Shafer,red wine,36.778261,-119.417932
73199,US,100,65.0,Oregon,Walla Walla Valley (OR),Syrah,Cayuse,red wine,43.804133,-120.554201
16010,US,100,100.0,California,Russian River Valley,Pinot Noir,Williams Selyem,red wine,36.778261,-119.417932
...,...,...,...,...,...,...,...,...,...,...
62352,Italy,98,175.0,Tuscany,Bolgheri Superiore,Red Blend,Tenuta dell'Ornellaia,red wine,43.771051,11.248621
68701,Australia,98,850.0,South Australia,South Australia,Shiraz,Penfolds,red wine,-30.000232,136.209155
62696,Italy,98,175.0,Tuscany,Bolgheri Superiore,Red Blend,Tenuta dell'Ornellaia,red wine,43.771051,11.248621
42567,US,98,110.0,California,Rutherford,Cabernet Blend,Rubicon Estate,red wine,36.778261,-119.417932
38527,US,98,175.0,California,Napa Valley,Bordeaux-style Red Blend,Colgin,red wine,36.778261,-119.417932

In [34]:
Top_Wine = pd.concat([Top_100_Red, Top_100_White], axis= 0, ignore_index=True)

In [35]:
Top_Wine.columns

Index(['country', 'points', 'price', 'province', 'region_1', 'variety',
       'winery', 'type', 'latitude', 'longtitude'],
      dtype='object')

In [36]:
Top_Wine_Data = Top_Wine.loc[:, ["country", "points", "price", "province", "variety", "winery", "type"]]
Top_Wine_Data

,country,points,price,province,variety,winery,type
0,US,100,65.0,Oregon,Syrah,Cayuse,red wine
1,Italy,100,460.0,Tuscany,Merlot,Tenuta dell'Ornellaia,red wine
2,US,100,215.0,California,Cabernet Sauvignon,Shafer,red wine
3,US,100,65.0,Oregon,Syrah,Cayuse,red wine
4,US,100,100.0,California,Pinot Noir,Williams Selyem,red wine
...,...,...,...,...,...,...,...
195,France,96,350.0,Champagne,Champagne Blend,Krug,white wine
196,France,96,500.0,Burgundy,Chardonnay,Bouchard Père & Fils,white wine
197,France,96,80.0,Alsace,Pinot Gris,Domaine Schoffit,white wine
198,US,96,50.0,California,Chardonnay,Gary Farrell,white wine
199,Italy,96,90.0,Northeastern Italy,Picolit,Livio Felluga,white wine

In [37]:
Top_Wine_Data_Table = Top_Wine_Data.sort_values(by=['points'], ascending=False)
Top_Wine_Data_Table

,country,points,price,province,variety,winery,type
0,US,100,65.0,Oregon,Syrah,Cayuse,red wine
13,US,100,245.0,California,Cabernet Blend,Sloan,red wine
106,Australia,100,300.0,Victoria,Muscat,Chambers Rosewood Vineyards,white wine
105,France,100,1400.0,Champagne,Chardonnay,Krug,white wine
104,France,100,848.0,Bordeaux,Bordeaux-style White Blend,Château Haut-Brion,white wine
...,...,...,...,...,...,...,...
190,France,96,500.0,Burgundy,Chardonnay,Etienne Sauzet,white wine
189,France,96,596.0,Burgundy,Chardonnay,Joseph Drouhin,white wine
188,US,96,180.0,California,Chardonnay,Hanzell,white wine
186,France,96,350.0,Burgundy,Chardonnay,Olivier Leflaive,white wine
199,Italy,96,90.0,Northeastern Italy,Picolit,Livio Felluga,white wine

In [38]:
print(Top_Wine_Data_Table.to_html())

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>country</th>
      <th>points</th>
      <th>price</th>
      <th>province</th>
      <th>variety</th>
      <th>winery</th>
      <th>type</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>US</td>
      <td>100</td>
      <td>65.0</td>
      <td>Oregon</td>
      <td>Syrah</td>
      <td>Cayuse</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>13</th>
      <td>US</td>
      <td>100</td>
      <td>245.0</td>
      <td>California</td>
      <td>Cabernet Blend</td>
      <td>Sloan</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>106</th>
      <td>Australia</td>
      <td>100</td>
      <td>300.0</td>
      <td>Victoria</td>
      <td>Muscat</td>
      <td>Chambers Rosewood Vineyards</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>105</th>
      <td>France</td>
      <td>100</td>
      <td>1400.0</td>
      <td>Champagne</td>
      <td>Chardonnay</td>
      <td>Krug</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>104</th>
      <td>France</td>
      <td>100</td>
      <td>848.0</td>
      <td>Bordeaux</td>
      <td>Bordeaux-style White Blend</td>
      <td>Château Haut-Brion</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>103</th>
      <td>Australia</td>
      <td>100</td>
      <td>300.0</td>
      <td>Victoria</td>
      <td>Muscat</td>
      <td>Chambers Rosewood Vineyards</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>102</th>
      <td>France</td>
      <td>100</td>
      <td>1400.0</td>
      <td>Champagne</td>
      <td>Chardonnay</td>
      <td>Krug</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>101</th>
      <td>Australia</td>
      <td>100</td>
      <td>300.0</td>
      <td>Victoria</td>
      <td>Muscat</td>
      <td>Chambers Rosewood Vineyards</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Italy</td>
      <td>100</td>
      <td>460.0</td>
      <td>Tuscany</td>
      <td>Merlot</td>
      <td>Tenuta dell'Ornellaia</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Italy</td>
      <td>100</td>
      <td>210.0</td>
      <td>Tuscany</td>
      <td>Prugnolo Gentile</td>
      <td>Avignonesi</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>15</th>
      <td>US</td>
      <td>100</td>
      <td>200.0</td>
      <td>California</td>
      <td>Cabernet Sauvignon</td>
      <td>Cardinale</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>14</th>
      <td>Italy</td>
      <td>100</td>
      <td>460.0</td>
      <td>Tuscany</td>
      <td>Merlot</td>
      <td>Tenuta dell'Ornellaia</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>100</th>
      <td>France</td>
      <td>100</td>
      <td>1400.0</td>
      <td>Champagne</td>
      <td>Chardonnay</td>
      <td>Krug</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Italy</td>
      <td>100</td>
      <td>195.0</td>
      <td>Tuscany</td>
      <td>Red Blend</td>
      <td>Giovanni Chiappini</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>8</th>
      <td>US</td>
      <td>100</td>
      <td>245.0</td>
      <td>California</td>
      <td>Cabernet Blend</td>
      <td>Sloan</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>11</th>
      <td>US</td>
      <td>100</td>
      <td>65.0</td>
      <td>Oregon</td>
      <td>Syrah</td>
      <td>Cayuse</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>3</th>
      <td>US</td>
      <td>100</td>
      <td>65.0</td>
      <td>Oregon</td>
      <td>Syrah</td>
      <td>Cayuse</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>4</th>
      <td>US</td>
      <td>100</td>
      <td>100.0</td>
      <td>California</td>
      <td>Pinot Noir</td>
      <td>Williams Selyem</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Italy</td>
      <td>100</td>
      <td>210.0</td>
      <td>Tuscany</td>
      <td>Prugnolo Gentile</td>
      <td>Avignonesi</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>6</th>
      <td>US</td>
      <td>100</td>
      <td>200.0</td>
      <td>California</td>
      <td>Cabernet Sauvignon</td>
      <td>Cardinale</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>7</th>
      <td>US</td>
      <td>100</td>
      <td>100.0</td>
      <td>California</td>
      <td>Pinot Noir</td>
      <td>Williams Selyem</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>2</th>
      <td>US</td>
      <td>100</td>
      <td>215.0</td>
      <td>California</td>
      <td>Cabernet Sauvignon</td>
      <td>Shafer</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Italy</td>
      <td>100</td>
      <td>195.0</td>
      <td>Tuscany</td>
      <td>Red Blend</td>
      <td>Giovanni Chiappini</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Italy</td>
      <td>100</td>
      <td>460.0</td>
      <td>Tuscany</td>
      <td>Merlot</td>
      <td>Tenuta dell'Ornellaia</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>22</th>
      <td>US</td>
      <td>99</td>
      <td>65.0</td>
      <td>Oregon</td>
      <td>Syrah</td>
      <td>Cayuse</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>21</th>
      <td>Italy</td>
      <td>99</td>
      <td>237.0</td>
      <td>Tuscany</td>
      <td>Prugnolo Gentile</td>
      <td>Avignonesi</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>45</th>
      <td>US</td>
      <td>99</td>
      <td>125.0</td>
      <td>Washington</td>
      <td>Cabernet Sauvignon</td>
      <td>Quilceda Creek</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>47</th>
      <td>Italy</td>
      <td>99</td>
      <td>200.0</td>
      <td>Tuscany</td>
      <td>Red Blend</td>
      <td>Tenuta dell'Ornellaia</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>48</th>
      <td>US</td>
      <td>99</td>
      <td>75.0</td>
      <td>California</td>
      <td>Pinot Noir</td>
      <td>Williams Selyem</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>49</th>
      <td>US</td>
      <td>99</td>
      <td>75.0</td>
      <td>Oregon</td>
      <td>Syrah</td>
      <td>Cayuse</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>50</th>
      <td>US</td>
      <td>99</td>
      <td>94.0</td>
      <td>California</td>
      <td>Pinot Noir</td>
      <td>Williams Selyem</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>51</th>
      <td>US</td>
      <td>99</td>
      <td>140.0</td>
      <td>Washington</td>
      <td>Syrah</td>
      <td>Charles Smith</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>52</th>
      <td>US</td>
      <td>99</td>
      <td>150.0</td>
      <td>California</td>
      <td>Cabernet Sauvignon</td>
      <td>David Arthur</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>19</th>
      <td>US</td>
      <td>99</td>
      <td>290.0</td>
      <td>California</td>
      <td>Red Blend</td>
      <td>Colgin</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>20</th>
      <td>Italy</td>
      <td>99</td>
      <td>320.0</td>
      <td>Tuscany</td>
      <td>Merlot</td>
      <td>Le Macchiole</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>43</th>
      <td>Italy</td>
      <td>99</td>
      <td>440.0</td>
      <td>Piedmont</td>
      <td>Nebbiolo</td>
      <td>Gaja</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>18</th>
      <td>Italy</td>
      <td>99</td>
      <td>175.0</td>
      <td>Piedmont</td>
      <td>Nebbiolo</td>
      <td>Mascarello Giuseppe e Figlio</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>17</th>
      <td>US</td>
      <td>99</td>
      <td>140.0</td>
      <td>Washington</td>
      <td>Syrah</td>
      <td>Charles Smith</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>107</th>
      <td>France</td>
      <td>99</td>
      <td>385.0</td>
      <td>Champagne</td>
      <td>Champagne Blend</td>
      <td>Moët &amp; Chandon</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>108</th>
      <td>France</td>
      <td>99</td>
      <td>385.0</td>
      <td>Champagne</td>
      <td>Champagne Blend</td>
      <td>Moët &amp; Chandon</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>109</th>
      <td>France</td>
      <td>99</td>
      <td>385.0</td>
      <td>Champagne</td>
      <td>Champagne Blend</td>
      <td>Moët &amp; Chandon</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>23</th>
      <td>Italy</td>
      <td>99</td>
      <td>200.0</td>
      <td>Tuscany</td>
      <td>Sangiovese</td>
      <td>Il Marroneto</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>44</th>
      <td>France</td>
      <td>99</td>
      <td>450.0</td>
      <td>Rhône Valley</td>
      <td>Syrah</td>
      <td>E. Guigal</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>46</th>
      <td>US</td>
      <td>99</td>
      <td>140.0</td>
      <td>Washington</td>
      <td>Syrah</td>
      <td>Charles Smith</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>42</th>
      <td>US</td>
      <td>99</td>
      <td>65.0</td>
      <td>Oregon</td>
      <td>Syrah</td>
      <td>Cayuse</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>28</th>
      <td>US</td>
      <td>99</td>
      <td>245.0</td>
      <td>California</td>
      <td>Cabernet Blend</td>
      <td>Harlan Estate</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>30</th>
      <td>Italy</td>
      <td>99</td>
      <td>200.0</td>
      <td>Tuscany</td>
      <td>Red Blend</td>
      <td>Tenuta dell'Ornellaia</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>31</th>
      <td>US</td>
      <td>99</td>
      <td>245.0</td>
      <td>California</td>
      <td>Cabernet Blend</td>
      <td>Harlan Estate</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>32</th>
      <td>France</td>
      <td>99</td>
      <td>450.0</td>
      <td>Rhône Valley</td>
      <td>Syrah</td>
      <td>E. Guigal</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>33</th>
      <td>Italy</td>
      <td>99</td>
      <td>200.0</td>
      <td>Tuscany</td>
      <td>Red Blend</td>
      <td>Tenuta dell'Ornellaia</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>34</th>
      <td>US</td>
      <td>99</td>
      <td>65.0</td>
      <td>Oregon</td>
      <td>Syrah</td>
      <td>Cayuse</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>41</th>
      <td>Italy</td>
      <td>99</td>
      <td>235.0</td>
      <td>Tuscany</td>
      <td>Red Blend</td>
      <td>Tenuta San Guido</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>27</th>
      <td>US</td>
      <td>99</td>
      <td>100.0</td>
      <td>California</td>
      <td>Cabernet Sauvignon</td>
      <td>Trefethen</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>26</th>
      <td>Italy</td>
      <td>99</td>
      <td>237.0</td>
      <td>Tuscany</td>
      <td>Prugnolo Gentile</td>
      <td>Avignonesi</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>25</th>
      <td>Italy</td>
      <td>99</td>
      <td>320.0</td>
      <td>Tuscany</td>
      <td>Merlot</td>
      <td>Le Macchiole</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>35</th>
      <td>France</td>
      <td>99</td>
      <td>450.0</td>
      <td>Rhône Valley</td>
      <td>Syrah</td>
      <td>E. Guigal</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>36</th>
      <td>Italy</td>
      <td>99</td>
      <td>440.0</td>
      <td>Piedmont</td>
      <td>Nebbiolo</td>
      <td>Gaja</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>37</th>
      <td>Italy</td>
      <td>99</td>
      <td>250.0</td>
      <td>Tuscany</td>
      <td>Merlot</td>
      <td>Tenuta dell'Ornellaia</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>38</th>
      <td>Italy</td>
      <td>99</td>
      <td>320.0</td>
      <td>Tuscany</td>
      <td>Merlot</td>
      <td>Le Macchiole</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>39</th>
      <td>France</td>
      <td>99</td>
      <td>2300.0</td>
      <td>Bordeaux</td>
      <td>Bordeaux-style Red Blend</td>
      <td>Château Latour</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>40</th>
      <td>US</td>
      <td>99</td>
      <td>75.0</td>
      <td>California</td>
      <td>Cabernet Sauvignon</td>
      <td>Stonestreet</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>24</th>
      <td>Italy</td>
      <td>99</td>
      <td>237.0</td>
      <td>Tuscany</td>
      <td>Prugnolo Gentile</td>
      <td>Avignonesi</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>29</th>
      <td>Italy</td>
      <td>99</td>
      <td>250.0</td>
      <td>Tuscany</td>
      <td>Merlot</td>
      <td>Tenuta dell'Ornellaia</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>110</th>
      <td>France</td>
      <td>98</td>
      <td>757.0</td>
      <td>Burgundy</td>
      <td>Chardonnay</td>
      <td>Bouchard Père &amp; Fils</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>99</th>
      <td>US</td>
      <td>98</td>
      <td>175.0</td>
      <td>California</td>
      <td>Bordeaux-style Red Blend</td>
      <td>Colgin</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>98</th>
      <td>US</td>
      <td>98</td>
      <td>110.0</td>
      <td>California</td>
      <td>Cabernet Blend</td>
      <td>Rubicon Estate</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>97</th>
      <td>Italy</td>
      <td>98</td>
      <td>175.0</td>
      <td>Tuscany</td>
      <td>Red Blend</td>
      <td>Tenuta dell'Ornellaia</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>96</th>
      <td>Australia</td>
      <td>98</td>
      <td>850.0</td>
      <td>South Australia</td>
      <td>Shiraz</td>
      <td>Penfolds</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>95</th>
      <td>Italy</td>
      <td>98</td>
      <td>175.0</td>
      <td>Tuscany</td>
      <td>Red Blend</td>
      <td>Tenuta dell'Ornellaia</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>113</th>
      <td>France</td>
      <td>98</td>
      <td>411.0</td>
      <td>Burgundy</td>
      <td>Chardonnay</td>
      <td>Domaine Leflaive</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>112</th>
      <td>France</td>
      <td>98</td>
      <td>411.0</td>
      <td>Burgundy</td>
      <td>Chardonnay</td>
      <td>Domaine Leflaive</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>128</th>
      <td>France</td>
      <td>98</td>
      <td>800.0</td>
      <td>Bordeaux</td>
      <td>Bordeaux-style White Blend</td>
      <td>Château Haut-Brion</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>114</th>
      <td>Australia</td>
      <td>98</td>
      <td>97.0</td>
      <td>Victoria</td>
      <td>Tokay</td>
      <td>Campbells</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>115</th>
      <td>France</td>
      <td>98</td>
      <td>757.0</td>
      <td>Burgundy</td>
      <td>Chardonnay</td>
      <td>Bouchard Père &amp; Fils</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>132</th>
      <td>France</td>
      <td>98</td>
      <td>800.0</td>
      <td>Bordeaux</td>
      <td>Bordeaux-style White Blend</td>
      <td>Château Haut-Brion</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>131</th>
      <td>Australia</td>
      <td>98</td>
      <td>86.0</td>
      <td>Victoria</td>
      <td>Tokay</td>
      <td>R.L. Buller &amp; Son</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>130</th>
      <td>France</td>
      <td>98</td>
      <td>800.0</td>
      <td>Bordeaux</td>
      <td>Bordeaux-style White Blend</td>
      <td>Château Haut-Brion</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>129</th>
      <td>France</td>
      <td>98</td>
      <td>200.0</td>
      <td>Bordeaux</td>
      <td>Bordeaux-style White Blend</td>
      <td>Château Climens</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>93</th>
      <td>Italy</td>
      <td>98</td>
      <td>135.0</td>
      <td>Tuscany</td>
      <td>Merlot</td>
      <td>Fattoria Petrolo</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>127</th>
      <td>France</td>
      <td>98</td>
      <td>200.0</td>
      <td>Bordeaux</td>
      <td>Bordeaux-style White Blend</td>
      <td>Château Climens</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>126</th>
      <td>France</td>
      <td>98</td>
      <td>170.0</td>
      <td>Champagne</td>
      <td>Champagne Blend</td>
      <td>Henriot</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>125</th>
      <td>France</td>
      <td>98</td>
      <td>410.0</td>
      <td>Burgundy</td>
      <td>Chardonnay</td>
      <td>Domaine Leflaive</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>124</th>
      <td>France</td>
      <td>98</td>
      <td>170.0</td>
      <td>Champagne</td>
      <td>Champagne Blend</td>
      <td>Henriot</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>123</th>
      <td>France</td>
      <td>98</td>
      <td>200.0</td>
      <td>Bordeaux</td>
      <td>Bordeaux-style White Blend</td>
      <td>Château Climens</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>122</th>
      <td>France</td>
      <td>98</td>
      <td>289.0</td>
      <td>Champagne</td>
      <td>Champagne Blend</td>
      <td>Louis Roederer</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>121</th>
      <td>France</td>
      <td>98</td>
      <td>757.0</td>
      <td>Burgundy</td>
      <td>Chardonnay</td>
      <td>Bouchard Père &amp; Fils</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>120</th>
      <td>France</td>
      <td>98</td>
      <td>411.0</td>
      <td>Burgundy</td>
      <td>Chardonnay</td>
      <td>Domaine Leflaive</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>119</th>
      <td>Australia</td>
      <td>98</td>
      <td>97.0</td>
      <td>Victoria</td>
      <td>Tokay</td>
      <td>Campbells</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>118</th>
      <td>Australia</td>
      <td>98</td>
      <td>97.0</td>
      <td>Victoria</td>
      <td>Tokay</td>
      <td>Campbells</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>117</th>
      <td>France</td>
      <td>98</td>
      <td>289.0</td>
      <td>Champagne</td>
      <td>Champagne Blend</td>
      <td>Louis Roederer</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>116</th>
      <td>France</td>
      <td>98</td>
      <td>170.0</td>
      <td>Champagne</td>
      <td>Champagne Blend</td>
      <td>Henriot</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>94</th>
      <td>Italy</td>
      <td>98</td>
      <td>320.0</td>
      <td>Tuscany</td>
      <td>Merlot</td>
      <td>Le Macchiole</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>111</th>
      <td>France</td>
      <td>98</td>
      <td>289.0</td>
      <td>Champagne</td>
      <td>Champagne Blend</td>
      <td>Louis Roederer</td>
      <td>white wine</td>
    </tr>
    <tr>
      <th>92</th>
      <td>US</td>
      <td>98</td>
      <td>110.0</td>
      <td>California</td>
      <td>Sparkling Blend</td>
      <td>Schramsberg</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>71</th>
      <td>Italy</td>
      <td>98</td>
      <td>135.0</td>
      <td>Tuscany</td>
      <td>Merlot</td>
      <td>Fattoria Petrolo</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>69</th>
      <td>Australia</td>
      <td>98</td>
      <td>125.0</td>
      <td>South Australia</td>
      <td>Shiraz</td>
      <td>Torbreck</td>
      <td>red wine</td>
    </tr>
    <tr>
      <th>68</th>
      <td>US</td>
      <td>98</td>
      <td>300.0</td>
      <td>California</td>
      <td>Bordeaux-style Red Blend</td>
      <td>Verité</td>
      <td>red wine</td>
    </tr>

In [39]:
Top_Wine.value_counts('variety')

variety
Chardonnay                    39
Champagne Blend               25
Syrah                         19
Merlot                        14
Cabernet Sauvignon            13
Bordeaux-style White Blend    12
Pinot Noir                    11
Red Blend                      9
Bordeaux-style Red Blend       7
Muscat                         7
Cabernet Blend                 6
Prugnolo Gentile               5
Tokay                          5
Cabernet Franc                 4
Pinot Gris                     4
Nebbiolo                       4
White Blend                    3
Muscadel                       3
Sangiovese                     2
Shiraz                         2
Sparkling Blend                2
Picolit                        2
Sangiovese Grosso              1
Tinto Fino                     1
dtype: int64

In [40]:
Top_Wine.value_counts('province')

province
California            45
Tuscany               40
Champagne             29
Burgundy              23
Victoria              15
Bordeaux              13
Oregon                10
Washington             7
Rhône Valley           4
Piedmont               4
Alsace                 4
South Australia        3
Northeastern Italy     2
Northern Spain         1
dtype: int64

In [41]:
Top_Wine.value_counts('type')

type
white wine    100
red wine      100
dtype: int64

# Hacky way of reading data (Total Top Wine)

In [42]:
TW = Top_Wine.groupby(['winery']).mean().sort_values(by=['points'], ascending=False).head(100)
TW

                       points  price   latitude  longtitude
winery
Shafer                  100.0  215.0  36.778261 -119.417932
Cardinale               100.0  200.0  36.778261 -119.417932
Sloan                   100.0  245.0  36.778261 -119.417932
Giovanni Chiappini      100.0  195.0  43.771051   11.248621
Tenuta dell'Ornellaia    99.1  283.0  43.771051   11.248621
...                       ...    ...        ...         ...
Joseph Drouhin           96.0  596.0  47.052505    4.383722
Gary Farrell             96.0   50.0  36.778261 -119.417932
Etienne Sauzet           96.0  500.0  47.052505    4.383722
Domaine Schoffit         96.0   80.0  48.318179    7.441624
Hanzell                  96.0  180.0  36.778261 -119.417932

[72 rows x 4 columns]

In [43]:
TW = Top_Wine.groupby(['winery']).mean().sort_values(by=['points'], ascending=False).head(10)
TW

                              points   price   latitude  longtitude
winery
Shafer                         100.0   215.0  36.778261 -119.417932
Cardinale                      100.0   200.0  36.778261 -119.417932
Sloan                          100.0   245.0  36.778261 -119.417932
Giovanni Chiappini             100.0   195.0  43.771051   11.248621
Tenuta dell'Ornellaia           99.1   283.0  43.771051   11.248621
Quilceda Creek                  99.0   125.0  47.751074 -120.740139
Il Marroneto                    99.0   200.0  43.771051   11.248621
Krug                            99.0  1137.5  30.203476  -92.016898
Mascarello Giuseppe e Figlio    99.0   175.0  45.052237    7.515388
Château Latour                  99.0  2300.0  44.837789   -0.579180

In [44]:
TW = Top_Wine.groupby(['winery']).mean().reset_index("winery")
twp = TW.loc[:, ["winery", "points", "price"]].sort_values(by=['points'], ascending=False).head(10)
twp

                          winery  points   price
60                        Shafer   100.0   215.0
5                      Cardinale   100.0   200.0
61                         Sloan   100.0   245.0
34            Giovanni Chiappini   100.0   195.0
64         Tenuta dell'Ornellaia    99.1   283.0
53                Quilceda Creek    99.0   125.0
39                  Il Marroneto    99.0   200.0
42                          Krug    99.0  1137.5
47  Mascarello Giuseppe e Figlio    99.0   175.0
13                Château Latour    99.0  2300.0

In [45]:
pr= twp["price"]
pr.tolist()

[215.0, 200.0, 245.0, 195.0, 283.0, 125.0, 200.0, 1137.5, 175.0, 2300.0]

In [46]:
TW = Top_Wine.groupby(['winery']).mean().reset_index("winery")
tw = TW.loc[:, ["winery", "points"]].sort_values(by=['points'], ascending=False).head(10)
tw

                          winery  points
60                        Shafer   100.0
5                      Cardinale   100.0
61                         Sloan   100.0
34            Giovanni Chiappini   100.0
64         Tenuta dell'Ornellaia    99.1
53                Quilceda Creek    99.0
39                  Il Marroneto    99.0
42                          Krug    99.0
47  Mascarello Giuseppe e Figlio    99.0
13                Château Latour    99.0

In [47]:
w= tw["winery"]
w.tolist()

['Shafer',
 'Cardinale',
 'Sloan',
 'Giovanni Chiappini',
 "Tenuta dell'Ornellaia",
 'Quilceda Creek',
 'Il Marroneto',
 'Krug',
 'Mascarello Giuseppe e Figlio',
 'Château Latour']

In [48]:
p= tw["points"]
p.tolist()

[100.0, 100.0, 100.0, 100.0, 99.1, 99.0, 99.0, 99.0, 99.0, 99.0]

In [49]:
# Red Wine Hack

In [50]:
RW = Top_100_Red.groupby(['winery']).mean().sort_values(by=['points'], ascending=False).head(10)
RW

                       points   price   latitude  longtitude
winery
Giovanni Chiappini      100.0   195.0  43.771051   11.248621
Cardinale               100.0   200.0  36.778261 -119.417932
Sloan                   100.0   245.0  36.778261 -119.417932
Shafer                  100.0   215.0  36.778261 -119.417932
Avignonesi               99.4   226.2  43.771051   11.248621
Tenuta dell'Ornellaia    99.1   283.0  43.771051   11.248621
Trefethen                99.0   100.0  36.778261 -119.417932
Cayuse                   99.0    67.5  43.804133 -120.554201
Château Latour           99.0  2300.0  44.837789   -0.579180
Tenuta San Guido         99.0   235.0  43.771051   11.248621

In [51]:
RW = Top_100_Red.groupby(['winery']).mean().reset_index("winery")
rw = RW.loc[:, ["winery", "points"]].sort_values(by=['points'], ascending=False).head(10)
rw

                   winery  points
18     Giovanni Chiappini   100.0
2               Cardinale   100.0
31                  Sloan   100.0
30                 Shafer   100.0
0              Avignonesi    99.4
34  Tenuta dell'Ornellaia    99.1
36              Trefethen    99.0
4                  Cayuse    99.0
6          Château Latour    99.0
33       Tenuta San Guido    99.0

In [52]:
redw= rw["winery"]
redw.tolist()

['Giovanni Chiappini',
 'Cardinale',
 'Sloan',
 'Shafer',
 'Avignonesi',
 "Tenuta dell'Ornellaia",
 'Trefethen',
 'Cayuse',
 'Château Latour',
 'Tenuta San Guido']

In [53]:
redp= rw["points"]
redp.tolist()

[100.0, 100.0, 100.0, 100.0, 99.4, 99.1, 99.0, 99.0, 99.0, 99.0]

In [54]:
# White Wine Hack

In [55]:
WW = Top_100_White.groupby(['winery']).mean().sort_values(by=['points'], ascending=False).head(10)
WW

                                points        price   latitude  longtitude
winery
Krug                         99.000000  1137.500000  30.203476  -92.016898
Moët & Chandon               99.000000   385.000000  30.203476  -92.016898
Chambers Rosewood Vineyards  98.500000   300.000000  28.805267  -97.003598
Château Haut-Brion           98.500000   812.000000  44.837789   -0.579180
R.L. Buller & Son            98.000000    86.000000  28.805267  -97.003598
Château Climens              98.000000   200.000000  44.837789   -0.579180
Bouchard Père & Fils         97.500000   692.750000  47.052505    4.383722
Henriot                      97.500000   177.500000  30.203476  -92.016898
Louis Roederer               97.428571   257.571429  30.203476  -92.016898
Campbells                    97.375000    94.000000  28.805267  -97.003598

In [56]:
WW = Top_100_White.groupby(['winery']).mean().reset_index("winery")
ww = WW.loc[:, ["winery", "points"]].sort_values(by=['points'], ascending=False).head(10)
ww

                         winery     points
21                         Krug  99.000000
25               Moët & Chandon  99.000000
4   Chambers Rosewood Vineyards  98.500000
6            Château Haut-Brion  98.500000
28            R.L. Buller & Son  98.000000
5               Château Climens  98.000000
2          Bouchard Père & Fils  97.500000
19                      Henriot  97.500000
24               Louis Roederer  97.428571
3                     Campbells  97.375000

In [57]:
whitew= ww["winery"]
whitew.tolist()

['Krug',
 'Moët & Chandon',
 'Chambers Rosewood Vineyards',
 'Château Haut-Brion',
 'R.L. Buller & Son',
 'Château Climens',
 'Bouchard Père & Fils',
 'Henriot',
 'Louis Roederer',
 'Campbells']

In [58]:
whitep= ww["points"]
whitep.tolist()

[99.0, 99.0, 98.5, 98.5, 98.0, 98.0, 97.5, 97.5, 97.42857142857143, 97.375]

In [59]:
tw.to_json(orient="table")

'{"schema":{"fields":[{"name":"index","type":"integer"},{"name":"winery","type":"string"},{"name":"points","type":"number"}],"primaryKey":["index"],"pandas_version":"0.20.0"},"data":[{"index":60,"winery":"Shafer","points":100.0},{"index":5,"winery":"Cardinale","points":100.0},{"index":61,"winery":"Sloan","points":100.0},{"index":34,"winery":"Giovanni Chiappini","points":100.0},{"index":64,"winery":"Tenuta dell\'Ornellaia","points":99.1},{"index":53,"winery":"Quilceda Creek","points":99.0},{"index":39,"winery":"Il Marroneto","points":99.0},{"index":42,"winery":"Krug","points":99.0},{"index":47,"winery":"Mascarello Giuseppe e Figlio","points":99.0},{"index":13,"winery":"Ch\\u00e2teau Latour","points":99.0}]}'

In [60]:
w=tw

In [61]:
tw.to_json("Top Winery Points.json")

In [62]:
tw.to_json()

'{"winery":{"60":"Shafer","5":"Cardinale","61":"Sloan","34":"Giovanni Chiappini","64":"Tenuta dell\'Ornellaia","53":"Quilceda Creek","39":"Il Marroneto","42":"Krug","47":"Mascarello Giuseppe e Figlio","13":"Ch\\u00e2teau Latour"},"points":{"60":100.0,"5":100.0,"61":100.0,"34":100.0,"64":99.1,"53":99.0,"39":99.0,"42":99.0,"47":99.0,"13":99.0}}'

In [63]:
Top_Wine.head()

,country,points,price,province,region_1,variety,winery,type,latitude,longtitude
0,US,100,65.0,Oregon,Walla Walla Valley (OR),Syrah,Cayuse,red wine,43.804133,-120.554201
1,Italy,100,460.0,Tuscany,Toscana,Merlot,Tenuta dell'Ornellaia,red wine,43.771051,11.248621
2,US,100,215.0,California,Stags Leap District,Cabernet Sauvignon,Shafer,red wine,36.778261,-119.417932
3,US,100,65.0,Oregon,Walla Walla Valley (OR),Syrah,Cayuse,red wine,43.804133,-120.554201
4,US,100,100.0,California,Russian River Valley,Pinot Noir,Williams Selyem,red wine,36.778261,-119.417932

In [64]:
Top_Wine.to_json("Top Wine Plottly.json", orient="records")

In [65]:
#white_final = Final_white_bubble4.copy()
#white_final.columns = ["tooltip", "name"]
#white_final["value"] = scaler.fit_transform(white_final["tooltip"].values.reshape(-1,1))*100

# white_data = json.loads(white_final.to_json(orient="records"))
# white_data_final = {
#     "name":"white wine",
#     "data": white_data
# }
# white_data_final

## Export Subset to Json

In [66]:
# Top_Wine.to_json('Top_Wine.json', index=True)
# Top_100_Red.to_json('Top_100_Red.json', index=True)
# Top_100_White.to_json('Top_100_White.json', index=True)

## Subset Data for Scattered Bubble Chart

In [67]:
# Final_Wine_Data.province.value_counts()

## Clean Data

In [68]:
# wine_bubble = Final_Wine_Data.loc[:, ["points", "province", "type"]]
# wine_bubble

In [69]:
# red_wine_bubble = wine_bubble.loc[wine_bubble.type == 'red wine'].sort_values(by=['province'], ascending=False)
# red_wine_bubble2 = red_wine_bubble.groupby('province').mean('points').round(1)

# merge_df4 = pd.merge(red_wine_bubble, red_wine_bubble2, on="province")
# merge_df5 = merge_df4.rename(columns = {'points_y': 'avg_points'})
# Final_red_bubble = merge_df5.loc[:, ["province", "type", "avg_points"]]
# Final_red_bubble

In [70]:
# Final_red_bubble2 = Final_red_bubble.loc[Final_red_bubble.duplicated(keep='last'), :]
# Final_red_bubble3 = Final_red_bubble2.drop_duplicates()
# Final_red_bubble3.info()

In [71]:
# white_wine_bubble = wine_bubble.loc[wine_bubble.type == 'white wine'].sort_values(by=['province'], ascending=False)
# white_wine_bubble2 = white_wine_bubble.groupby('province').mean('points').round(1)

# merge_df4 = pd.merge(white_wine_bubble, white_wine_bubble2, on="province")
# merge_df5 = merge_df4.rename(columns = {'points_y': 'avg_points'})
# Final_white_bubble = merge_df5.loc[:, ["province", "type", "avg_points"]]
# Final_white_bubble

In [72]:
# Final_white_bubble2 = Final_white_bubble.loc[Final_red_bubble.duplicated(keep='last'), :]
# Final_white_bubble3 = Final_white_bubble2.drop_duplicates()
# Final_white_bubble3.info()

In [73]:
# Final_wine_bubble = pd.concat([Final_red_bubble3, Final_white_bubble3], axis= 0, ignore_index=True)
# Final_wine_bubble

## Export Subset to Json

In [74]:
# Final_wine_bubble.to_json('Bubble_Wine2.js', index=True)

In [75]:
# Final_red_bubble4 = Final_red_bubble3.loc[:, ["avg_points", "province"]]
# Final_red_bubble4

In [76]:
# Final_white_bubble4 = Final_white_bubble3.loc[:, ["avg_points", "province"]]
# Final_white_bubble4

## Transforming Scattered Bubble Data

In [77]:
# scaler = MinMaxScaler()

In [78]:
# white_final = Final_white_bubble4.copy()
# white_final.columns = ["tooltip", "name"]
# white_final["value"] = scaler.fit_transform(white_final["tooltip"].values.reshape(-1,1))*100

# white_data = json.loads(white_final.to_json(orient="records"))
# white_data_final = {
#     "name":"white wine",
#     "data": white_data
# }
# white_data_final

In [79]:
# red_final = Final_red_bubble4.copy()
# red_final.columns = ["tooltip", "name"]
# red_final["value"] = scaler.fit_transform(red_final["tooltip"].values.reshape(-1,1))*100

# red_data = json.loads(red_final.to_json(orient="records"))
# red_data_final = {
#     "name":"red wine",
#     "data": red_data
# }
# red_data_final

In [80]:
#Final_red_bubble4.to_json('Final_red_bubble4.js', index=False)
#Final_white_bubble4.to_json('Final_white_bubble4.js', index=False)

In [81]:
#final = [white_data_final, red_data_final]
#final

In [82]:
#white_wine_dict = dict(zip(Final_white_bubble4.province, Final_white_bubble4.avg_points))
#white_wine_dict

In [83]:
#red_wine_dict = dict(zip(Final_red_bubble4.province, Final_red_bubble4.avg_points))
#red_wine_dict